### ISSUE TITLE
Regarding Connections and Hardware Replacement

### ISSUE THREAD

**Issue by anuragvermaa** [topisani/OTTO-proto-1#2]
I really love this project and am more than willing to contribute as much as I can and as much is left from completion. So, I wanted to do a custom build, but had few doubts, i.e.
1. Can I use any I2S codec?
2. Needed some help with hardware connections.

**Comment by topisani** [comment]
this repository has been subsumed. Take a look at the info [here](https://otto-project.github.io/docs). In a few months the new hardware will be finished
